"""empty message

Revision ID: 743fdf4bebe0
Revises: d6aa5413126c
Create Date: 2023-04-10 20:05:32.585399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '743fdf4bebe0'
down_revision = 'd6aa5413126c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('story_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'create_story', ['story_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('story_id')

    # ### end Alembic commands ###
