"""empty message

Revision ID: 7f770da3c5a2
Revises: 4ae50e535491
Create Date: 2023-04-10 19:52:05.731634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f770da3c5a2'
down_revision = '4ae50e535491'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['create_story.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=256), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('create_story', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('storydescription', sa.String(length=256), nullable=False))
        batch_op.drop_constraint('create_story_chapters_key', type_='unique')
        batch_op.drop_constraint('create_story_likes_key', type_='unique')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('likes')
        batch_op.drop_column('chapters')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('create_story', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('chapters', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('likes', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint('create_story_likes_key', ['likes'])
        batch_op.create_unique_constraint('create_story_chapters_key', ['chapters'])
        batch_op.drop_column('storydescription')
        batch_op.drop_column('user_id')

    op.drop_table('comment')
    op.drop_table('chapters')
    # ### end Alembic commands ###
