"""empty message

Revision ID: 8072bd892101
Revises: 743fdf4bebe0
Create Date: 2023-04-10 20:21:02.239037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8072bd892101'
down_revision = '743fdf4bebe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint('comment_story_id_fkey', type_='foreignkey')
        batch_op.drop_column('story_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('story_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('comment_story_id_fkey', 'create_story', ['story_id'], ['id'])

    # ### end Alembic commands ###
