"""empty message

Revision ID: d6aa5413126c
Revises: 7f770da3c5a2
Create Date: 2023-04-10 19:53:15.287438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6aa5413126c'
down_revision = '7f770da3c5a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes', sa.BigInteger(), nullable=True))

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes', sa.BigInteger(), nullable=True))

    with op.batch_alter_table('create_story', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes', sa.BigInteger(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('create_story', schema=None) as batch_op:
        batch_op.drop_column('likes')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('likes')

    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.drop_column('likes')

    # ### end Alembic commands ###
