"""empty message

Revision ID: efe2695fa6d8
Revises: 
Create Date: 2023-04-04 21:55:49.146511

"""
from alembic import op
import sqlalchemy as sa


whose add ! Doctype Html

Js.app

bootstrap.import. bootstrap. getbootstrap.com/getbootstrap//download


# revision identifiers, used by Alembic.
revision = 'efe2695fa6d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
